export enum OperationAction{
  BUY = 'BUY',
  SELL = 'SELL'

}
export const symbols: { value: string, label: string }[] = [
    { value: 'AAPL', label: 'AAPL (Apple Inc.)' },
    { value: 'GOOG', label: 'GOOGL (Alphabet Inc.)' },
    { value: 'MSFT', label: 'MSFT (Microsoft Corporation)' },
    { value: 'AMZN', label: 'AMZN (Amazon.com Inc.)' },
    { value: 'META', label: 'META (Meta Platforms, Inc.)' },
    { value: 'TSLA', label: 'TSLA (Tesla, Inc.)' },
    { value: 'BRK-A', label: 'BRK-A (Berkshire Hathaway Inc.)' },
    { value: 'BRK-B', label: 'BRK-B (Berkshire Hathaway Inc.)' },
    { value: 'JPM', label: 'JPM (JPMorgan Chase & Co.)' },
    { value: 'JNJ', label: 'JNJ (Johnson & Johnson)' },
    { value: 'V', label: 'V (Visa Inc.)' },
    { value: 'WMT', label: 'WMT (Walmart Inc.)' },
    { value: 'PG', label: 'PG (Procter & Gamble Company)' },
    { value: 'UNH', label: 'UNH (UnitedHealth Group Incorporated)' },
    { value: 'MA', label: 'MA (Mastercard Incorporated)' },
    { value: 'NVDA', label: 'NVDA (NVIDIA Corporation)' },
    { value: 'HD', label: 'HD (The Home Depot, Inc.)' },
    { value: 'PYPL', label: 'PYPL (PayPal Holdings, Inc.)' },
    { value: 'DIS', label: 'DIS (The Walt Disney Company)' },
    { value: 'BAC', label: 'BAC (Bank of America Corporation)' },
    { value: 'VZ', label: 'VZ (Verizon Communications Inc.)' },
    { value: 'INTC', label: 'INTC (Intel Corporation)' },
    { value: 'CSCO', label: 'CSCO (Cisco Systems, Inc.)' },
    { value: 'KO', label: 'KO (The Coca-Cola Company)' },
    { value: 'CMCSA', label: 'CMCSA (Comcast Corporation)' },
    { value: 'T', label: 'T (AT&T Inc.)' },
    { value: 'PEP', label: 'PEP (PepsiCo, Inc.)' },
    { value: 'ABBV', label: 'ABBV (AbbVie Inc.)' },
    { value: 'PFE', label: 'PFE (Pfizer Inc.)' },
    { value: 'ORCL', label: 'ORCL (Oracle Corporation)' },
    { value: 'NKE', label: 'NKE (NIKE, Inc.)' },
    { value: 'MRK', label: 'MRK (Merck & Co., Inc.)' },
    { value: 'CRM', label: 'CRM (salesforce.com, inc.)' },
    { value: 'WFC', label: 'WFC (Wells Fargo & Company)' },
    { value: 'BA', label: 'BA (The Boeing Company)' },
    { value: 'XOM', label: 'XOM (Exxon Mobil Corporation)' },
    { value: 'COST', label: 'COST (Costco Wholesale Corporation)' },
    { value: 'IBM', label: 'IBM (International Business Machines Corporation)' },
    { value: 'DISCA', label: 'DISCA (Discovery, Inc.)' },
    { value: 'NFLX', label: 'NFLX (Netflix, Inc.)' },
    { value: 'FDX', label: 'FDX (FedEx Corporation)' },
    { value: 'GS', label: 'GS (The Goldman Sachs Group, Inc.)' },
    { value: 'ABT', label: 'ABT (Abbott Laboratories)' },
    { value: 'TMO', label: 'TMO (Thermo Fisher Scientific Inc.)' },
    { value: 'MS', label: 'MS (Morgan Stanley)' },
    { value: 'CVX', label: 'CVX (Chevron Corporation)' },
    { value: 'LMT', label: 'LMT (Lockheed Martin Corporation)' },
    { value: 'ADBE', label: 'ADBE (Adobe Inc.)' },
    { value: 'SBUX', label: 'SBUX (Starbucks Corporation)' },
    { value: 'DHR', label: 'DHR (Danaher Corporation)' },
    { value: 'CAT', label: 'CAT (Caterpillar Inc.)' },
    { value: 'UPS', label: 'UPS (United Parcel Service, Inc.)' },
    { value: 'MMM', label: 'MMM (3M Company)' },
    { value: 'AVGO', label: 'AVGO (Broadcom Inc.)' },
    { value: 'MO', label: 'MO (Altria Group, Inc.)' },
    { value: 'BKNG', label: 'BKNG (Booking Holdings Inc.)' },
    { value: 'RTX', label: 'RTX (Raytheon Technologies Corporation)' },
    { value: 'SCHW', label: 'SCHW (The Charles Schwab Corporation)' },
    { value: 'NOW', label: 'NOW (ServiceNow, Inc.)' },
    { value: 'TGT', label: 'TGT (Target Corporation)' },
    { value: 'BIIB', label: 'BIIB (Biogen Inc.)' },
    { value: 'AABA', label: 'AABA (Altaba Inc.)' },
    { value: 'C', label: 'C (Citigroup Inc.)' },
    { value: 'BLK', label: 'BLK (BlackRock, Inc.)' },
    { value: 'USB', label: 'USB (U.S. Bancorp)' },
    { value: 'GM', label: 'GM (General Motors Company)' },
    { value: 'DAL', label: 'DAL (Delta Air Lines, Inc.)' },
    { value: 'LUV', label: 'LUV (Southwest Airlines Co.)' },
    { value: 'AAL', label: 'AAL (American Airlines Group Inc.)' },
    { value: 'UAL', label: 'UAL (United Airlines Holdings, Inc.)' },
    { value: 'AAP', label: 'AAP (Advance Auto Parts, Inc.)' },
    { value: 'OXY', label: 'OXY (Occidental Petroleum Corporation)' },
    { value: 'MET', label: 'MET (MetLife, Inc.)' },
    { value: 'CVS', label: 'CVS (CVS Health Corporation)' },
    { value: 'LMT', label: 'LMT (Lockheed Martin Corporation)' },
    { value: 'HPE', label: 'HPE (Hewlett Packard Enterprise Company)' },
    { value: 'PSX', label: 'PSX (Phillips 66)' },
    { value: 'SLB', label: 'SLB (Schlumberger Limited)' },
    { value: 'WYNN', label: 'WYNN (Wynn Resorts, Limited)' },
    { value: 'MGM', label: 'MGM (MGM Resorts International)' },
    { value: 'BKR', label: 'BKR (Baker Hughes Company)' },
    { value: 'HAL', label: 'HAL (Halliburton Company)' },
    { value: 'LVS', label: 'LVS (Las Vegas Sands Corp.)' },
    { value: 'USB', label: 'USB (U.S. Bancorp)' },
    { value: 'CCL', label: 'CCL (Carnival Corporation & Plc)' },
    { value: 'NCLH', label: 'NCLH (Norwegian Cruise Line Holdings Ltd.)' },
    { value: 'RCL', label: 'RCL (Royal Caribbean Group)' },
    { value: 'MRO', label: 'MRO (Marathon Oil Corporation)' },
    { value: 'SLB', label: 'SLB (Schlumberger Limited)' },
    { value: 'DVN', label: 'DVN (Devon Energy Corporation)' },
    { value: 'XOM', label: 'XOM (Exxon Mobil Corporation)' },
    { value: 'APA', label: 'APA (APA Corporation)' },
    { value: 'EOG', label: 'EOG (EOG Resources, Inc.)' },
    { value: 'COP', label: 'COP (ConocoPhillips)' },
    { value: 'FANG', label: 'FANG (Diamondback Energy, Inc.)' },
    { value: 'MPC', label: 'MPC (Marathon Petroleum Corporation)' },
    { value: 'PSX', label: 'PSX (Phillips 66)' },
    { value: 'VLO', label: 'VLO (Valero Energy Corporation)' },
    { value: 'NOV', label: 'NOV (NOV Inc.)' },
    { value: 'WMB', label: 'WMB (The Williams Companies, Inc.)' },
    { value: 'PXD', label: 'PXD (Pioneer Natural Resources Company)' },
    { value: 'COG', label: 'COG (Cabot Oil & Gas Corporation)' },
    { value: 'OXY', label: 'OXY (Occidental Petroleum Corporation)' },
    { value: 'MRO', label: 'MRO (Marathon Oil Corporation)' },
    { value: 'DVN', label: 'DVN (Devon Energy Corporation)' },
    { value: 'HAL', label: 'HAL (Halliburton Company)' },
    { value: 'SLB', label: 'SLB (Schlumberger Limited)' },
    { value: 'APA', label: 'APA (APA Corporation)' },
    { value: 'EOG', label: 'EOG (EOG Resources, Inc.)' },
    { value: 'COP', label: 'COP (ConocoPhillips)' },
    { value: 'FANG', label: 'FANG (Diamondback Energy, Inc.)' },
    { value: 'MPC', label: 'MPC (Marathon Petroleum Corporation)' },
    { value: 'PSX', label: 'PSX (Phillips 66)' },
    { value: 'VLO', label: 'VLO (Valero Energy Corporation)' },
    { value: 'NOV', label: 'NOV (NOV Inc.)' },
    { value: 'WMB', label: 'WMB (The Williams Companies, Inc.)' },
    { value: 'PXD', label: 'PXD (Pioneer Natural Resources Company)' },
    { value: 'COG', label: 'COG (Cabot Oil & Gas Corporation)' },
    { value: 'XAUUSD=X', label: 'XAUUSD=X (Gold)' },
    { value: 'XAGUSD=X', label: 'XAGUSD=X (Silver)' },
    { value: 'CL=F', label: 'CL=F (Crude Oil)' },
    { value: 'NG=F', label: 'NG=F (Natural Gas)' },
    { value: 'HG=F', label: 'HG=F (Copper)' },
    { value: 'SI=F', label: 'SI=F (Silver)' },
    { value: 'GC=F', label: 'GC=F (Gold)' },
    { value: 'PL=F', label: 'PL=F (Platinum)' },
    { value: 'PA=F', label: 'PA=F (Palladium)' },
    { value: 'KC=F', label: 'KC=F (Coffee)' },
    { value: 'CC=F', label: 'CC=F (Cocoa)' },
    { value: 'SB=F', label: 'SB=F (Sugar)' },
    { value: 'ZW=F', label: 'ZW=F (Wheat)' },
    { value: 'ZC=F', label: 'ZC=F (Corn)' },
    { value: 'ZS=F', label: 'ZS=F (Soybeans)' },
    { value: 'ZO=F', label: 'ZO=F (Oats)' },
    { value: 'ZL=F', label: 'ZL=F (Soybean Oil)' },
    { value: 'ZM=F', label: 'ZM=F (Soybean Meal)' },
    { value: 'ZT=F', label: 'ZT=F (2-Year Treasury Note Futures)' },
    { value: 'ZF=F', label: 'ZF=F (5-Year Treasury Note Futures)' },
    { value: 'ZN=F', label: 'ZN=F (10-Year Treasury Note Futures)' },
    { value: 'ZB=F', label: 'ZB=F (30-Year Treasury Bond Futures)' },
    { value: 'YM=F', label: 'YM=F (E-Mini Dow Jones Industrial Average Futures)' },
    { value: 'ES=F', label: 'ES=F (E-Mini S&P 500 Futures)' },
    { value: 'NQ=F', label: 'NQ=F (E-Mini Nasdaq 100 Futures)' },
    { value: 'RTY=F', label: 'RTY=F (E-Mini Russell 2000 Futures)' },
    { value: 'BZ=F', label: 'BZ=F (Brent Crude Oil Futures)' },
    { value: 'NG=F', label: 'NG=F (Natural Gas Futures)' },
    { value: 'HG=F', label: 'HG=F (Copper Futures)' },
    { value: 'SI=F', label: 'SI=F (Silver Futures)' },
    { value: 'GC=F', label: 'GC=F (Gold Futures)' },
    { value: 'PL=F', label: 'PL=F (Platinum Futures)' },
    { value: 'PA=F', label: 'PA=F (Palladium Futures)' },
    { value: 'HG=F', label: 'HG=F (High Grade Copper Futures)' },
    { value: 'PL=F', label: 'PL=F (Platinum Futures)' },
    { value: 'PA=F', label: 'PA=F (Palladium Futures)' },
    { value: 'SB=F', label: 'SB=F (Sugar Futures)' },
    { value: 'CC=F', label: 'CC=F (Cocoa Futures)' },
    { value: 'KC=F', label: 'KC=F (Coffee Futures)' },
  ];

